In [18]:
import json
import numpy as np
import pickle

ModuleNotFoundError: No module named 'faiss'

In [5]:
dist_to_cent_path = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location/dist_to_cent.npy"
kmeans_centroids_path = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location/kmeans_centroids.npy"
kmeans_index_path = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location/kmeans_index.pickle"
nearest_cent_path = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location/nearest_cent.npy"

In [6]:
dist_to_cent = np.load(dist_to_cent_path)

In [9]:
dist_to_cent

array([0.7667998 , 0.78590834, 0.8089526 , 0.872614  , 0.7806274 ,
       0.82157815, 0.878303  , 0.896036  , 0.83841544, 0.81058663,
       0.8164714 , 0.9334228 , 0.87191916, 0.857003  , 0.75796515,
       0.8368749 , 0.8095121 , 0.8079305 , 0.8513582 , 0.8626343 ,
       0.7495757 , 0.8038612 , 0.80777526, 0.845601  , 0.8633273 ,
       0.8520894 , 0.7658187 , 0.8260699 , 0.7720321 , 0.7678662 ,
       0.8256133 , 0.8302088 , 0.7872035 , 0.91754556, 0.84822404,
       0.8686685 , 0.862296  , 0.84783274, 0.8561755 , 0.83397907,
       0.8327508 , 0.79492223, 0.81809556, 0.90405583, 0.84771127,
       0.8754141 , 0.8309518 , 0.8903014 , 0.83447987, 0.8409411 ,
       0.9505668 , 0.8481279 , 0.8828817 , 0.87489694, 0.7756894 ,
       0.7927546 , 0.9117255 , 0.88473314, 0.77592623, 0.8069709 ,
       0.74666965, 0.8938621 , 0.8133255 , 0.79208803, 0.8727699 ,
       0.7952133 , 0.7927403 , 0.79777455, 0.9043035 , 0.87806946,
       0.8454547 , 0.72161704, 0.9212456 , 0.8459643 , 0.87903

In [10]:
kmeans_centroids = np.load(kmeans_centroids_path)

In [13]:
kmeans_centroids

array([[-0.00427967, -0.00791776, -0.00489135, ..., -0.00806087,
         0.00175193,  0.01607627],
       [ 0.02567953,  0.02325489,  0.00904939, ...,  0.0319884 ,
         0.00974288,  0.02133959],
       [-0.01053922,  0.01305528, -0.01367826, ..., -0.02694197,
        -0.00970106,  0.0080921 ],
       ...,
       [-0.0098042 , -0.01136418,  0.00641898, ...,  0.00570991,
         0.03376765, -0.00284506],
       [ 0.02022869, -0.00304744,  0.00474573, ...,  0.00041617,
         0.0415779 ,  0.01136685],
       [-0.00618376,  0.00239974, -0.03328286, ..., -0.00216615,
         0.02674527,  0.02687906]], dtype=float32)

In [14]:
nearest_cent = np.load(nearest_cent_path)

In [15]:
nearest_cent

array([14,  3,  6, 16, 12, 16,  9,  3,  4,  6, 12,  9,  4,  6, 12, 17,  4,
        3,  7, 16, 14,  4, 16,  6,  8,  0, 16,  6,  4, 16, 16,  6,  9,  3,
        7, 17, 16,  8, 17,  4,  7, 12, 12,  7,  4,  4, 16,  7,  6,  4,  2,
       16,  3,  4,  6, 14, 10, 17, 14,  6, 13,  8,  7, 12,  3,  4,  1,  6,
        8, 13,  5, 17,  9,  4, 16,  3, 19, 13,  2,  4, 11,  4,  5,  0, 16,
       14,  7,  6, 16,  4,  4,  8, 16,  4,  6,  4, 16,  5,  6,  1,  3, 17,
       16, 19,  4,  5,  4, 17,  6, 15,  0, 14, 14, 12, 16, 14, 18,  4, 16,
        5, 14, 14, 14,  8,  1,  4, 16, 11,  6, 12,  6,  0,  5,  1,  1,  4,
        3, 14,  3, 16,  9,  3, 15,  5,  1, 10, 16, 16, 11,  6,  4, 16,  4,
        9,  3, 12,  4, 12,  4, 11, 12,  5, 17, 17, 19, 12,  8,  5, 18,  0,
       12,  6, 16,  4,  3, 16,  9, 14,  6,  3, 16,  6,  7, 17, 13, 16,  4,
        6,  7, 17,  4,  6, 19,  8,  3,  4,  3, 16,  6,  4])

In [17]:
with open(kmeans_index_path, 'rb') as kmeans_index_file:
    kmeans_index = pickle.load(kmeans_index_file)

ModuleNotFoundError: No module named 'faiss'

In [22]:
!pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 71.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 60.4 MB/s eta 0:00:00

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python -m pip install --upgrade pip


In [23]:
import pandas as pd

/tmp/ipykernel_2094/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [25]:
dataset_json_file_path = "./../../codealpaca/data/code_alpaca_2k.json"

In [26]:
df = pd.read_json(dataset_json_file_path)
df['ID'] = range(0, len(df))

In [31]:
data_centroids_map = dict()

In [33]:
i = 0 
while i < len(nearest_cent):
    if nearest_cent[i] in data_centroids_map:
        data_centroids_map[nearest_cent[i]].append(i)
    else:
        data_centroids_map[nearest_cent[i]] = [i]
    i += 1

In [36]:
cluster_14 = data_centroids_map[14]

In [38]:
for idx in cluster_14:
    print(df.iloc[idx].instruction)

What are the distinct values from the given list?
Rewrite this JavaScript function to use ES6 syntax.
What is a possible way to check whether an element exists in a set?
Generate a correct logic for updating a data field in a table.
Suggest a modification to the following C code.
Develop a code snippet to get the  value of the key 'name' from the following dictionary.
Below is a piece of code in which task you need to make it compatible with Python 3.
Write a single line of code to convert this list to a set.
Write a code snippet to get the fifth element of the following list.
Write a code snippet to change the third-element in the following tuple.
Using the following data structure, write a code snippet to get the value of the key 'dob'.
Convert a given temperature from Celsius to Fahrenheit
Convert the given list ['apple', 'banana', 'cherry', 'mango'] to a Dictionary


In [40]:
cluster_3 = data_centroids_map[3]

In [41]:
for idx in cluster_3:
    print(df.iloc[idx].instruction)

How would you order a sequence of letters alphabetically?
How would you sort a list of integer numbers in descending order?
Suppose you have an array of objects and you want to sort them by the value of a given key. Write a JavaScript function to do the sorting.
Write a Java program to sort an array of integers in descending order.
Rewrite the given code to sort the list of numbers in ascending order.
Create a Python function to sort a string in descending order.
Implement the bubble sort algorithm in C++.
Sort the numbers in a given list from biggest to smallest using Ruby.
Write an algorithm to traverse a binary tree
Explain the working of bubble sort algorithm.
Explain what is a deque (double-ended queue) in Python.
Design a Java program to sort elements in an array using insertion sort.
Sort this input array [1, 6, 4, 3, 0, 9] in ascending order.
Write a code to sort an input array of 3 numbers [10, 9, 8] in Descending Order.
Implement a Java program to sort an array of strings alp

In [43]:
cluster_6 = data_centroids_map[6]

In [44]:
for idx in cluster_6:
    print(df.iloc[idx].instruction)

Write a JavaScript code to loop over all elements in the given array.
Write an if-else statement in Java that checks if a given number is between 0 and 10.
Write a Java code to find the sum of two numbers.
Create a C++ program to compute the sum of two numbers.
Create a C# program to perform a linear search on an array.
Write a JavaScript function to generate a random number between 0 to 10.
Create a function in Java that takes in an integer n as a parameter and returns the sum of the first n natural numbers.
Create a C++ function that checks if a given integer is an Armstrong number.
Create a C++ class to calculate the maximum value in an array.
Create a Swift function to find the smallest element in an array.
Write a piece of Python code to generate a random number between 1 and 10.
Generate a C program to find the sum of all the elements in a given array.
Create a JavaScript array containing 5 fruits.
Write a JavaScript function that takes two numbers as parameters and returns the s

In [46]:
cluster_4 = data_centroids_map[4]

In [47]:
for idx in cluster_4:
    print(df.iloc[idx].instruction)

Write a function in JavaScript that takes in a string and returns its length.
Write a JavaScript program to check if a given string is a palindrome.
Create a ruby function that takes two strings as parameters and returns true if the two strings are anagrams.
Create an array of strings with only the elements of another array that have a length longer than 5 characters.
Create a php code to capitalize the first letter of every word in a string.
Write a Python program to check if a given string contains any punctuation character or not.
Create a Java program to print out the words of a given string in reverse order.
Create a JavaScript program that counts the number of vowels in a given string.
Create a JavaScript program that takes two strings and returns true if they are pairwise anagrams of each other.
Create a JavaScript program that takes in a string and returns the number of pairs of matching letters in the string.
Find the longest word in a sentence using JavaScript.
Write a Java p

In [48]:
# Assign and sort clusters

In [50]:
sorted_cluster_path_4 = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/sorted_clusters/cluster_4.npy"

In [51]:
scluster_4 = np.load(sorted_cluster_path_4)

In [56]:
# example_paths, cluster_items, cluster_dists_to_cent, cluster_label
scluster_4

array([[1.86000000e+02, 1.86000000e+02, 2.79951513e-01, 4.00000000e+00],
       [2.80000000e+01, 2.80000000e+01, 2.27967918e-01, 4.00000000e+00],
       [6.50000000e+01, 6.50000000e+01, 2.04786718e-01, 4.00000000e+00],
       [1.25000000e+02, 1.25000000e+02, 2.01089382e-01, 4.00000000e+00],
       [2.10000000e+01, 2.10000000e+01, 1.96138799e-01, 4.00000000e+00],
       [9.50000000e+01, 9.50000000e+01, 1.92661226e-01, 4.00000000e+00],
       [1.95000000e+02, 1.95000000e+02, 1.91277623e-01, 4.00000000e+00],
       [1.60000000e+01, 1.60000000e+01, 1.90487921e-01, 4.00000000e+00],
       [8.90000000e+01, 8.90000000e+01, 1.76633060e-01, 4.00000000e+00],
       [1.35000000e+02, 1.35000000e+02, 1.75875664e-01, 4.00000000e+00],
       [1.04000000e+02, 1.04000000e+02, 1.75238609e-01, 4.00000000e+00],
       [9.00000000e+01, 9.00000000e+01, 1.75217211e-01, 4.00000000e+00],
       [1.06000000e+02, 1.06000000e+02, 1.73351407e-01, 4.00000000e+00],
       [1.52000000e+02, 1.52000000e+02, 1.72781110e

In [62]:
df.iloc[186].instruction # furthest

'Design a regex expression that validates a given password based on a given criteria.'

In [63]:
df.iloc[45].instruction # closest

'Create a JavaScript program that counts the number of vowels in a given string.'

In [64]:
df.iloc[53].instruction # 2nd closest

'Create a JavaScript program that takes in a string and returns the number of pairs of matching letters in the string.'

In [65]:
df.iloc[12].instruction # 2nd closest

'Write a JavaScript program to check if a given string is a palindrome.'

In [66]:
# ran semdedup

In [67]:
c_4_to_remove_path = "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location/dataframes/cluster_4.pkl"

In [71]:
with open(c_4_to_remove_path, 'rb') as c_4_to_remove_file:
    c_4_to_remove = pickle.load(c_4_to_remove_file)

In [72]:
c_4_to_remove

indices  eps=0.9  eps=0.95  eps=0.98
0        17    False     False     False
1        23     True      True      True
2         1     True      True      True
3        13     True      True      True
4        29     True      True      True
5        11     True      True      True
6         7     True      True      True
7         9     True      True      True
8        27     True      True      True
9        12     True      True      True
10       10     True      True      True
11        8     True      True      True
12        3     True      True      True
13       15     True      True      True
14       21     True      True      True
15       16     True      True      True
16       30     True      True      True
17       18     True      True      True
18        6     True      True      True
19       20     True      True      True
20        0     True      True      True
21       22     True      True      True
22       26     True      True      True
23       14     True      True      True
24       28     True      True      True
25       19     True      True      True
26        4     True      True      True
27        2     True      True      True
28       25     True      True      True
29       31     True      True      True
30        5     True      True      True
31       24     True      True      True

In [77]:
df.iloc[int(scluster_4[17][0])].instruction

'Write a function in JavaScript that takes in a string and returns its length.'

In [78]:
# running extraction

In [79]:
scluster_4[17][0]

8.0